podTemplate(label: 'mypod', cloud: 'openshift', containers: [
    containerTemplate(name: 'maven', ttyEnabled: true, command: 'cat',
                      workingDir: '/home/jenkins',
                      alwaysPullImage: true,
                      resourceRequestCpu: '1000m',
                      resourceLimitCpu: '2000m',
                      resourceRequestMemory: '512Mi',
                      resourceLimitMemory: '1024Mi',
                      envVars: [envVar(key: 'MAVEN_MIRROR_URL', value: '${MAVEN_MIRROR_URL}')])
  ]) {

    node('mypod') {
        stage('Build') {
          git url: '${GIT_REPO}', branch: "${GIT_REF}"
          container('hogajama-maven') {
            sh "mvn clean test -f Hogajama/pom.xml"
          }
       }
   }
}
