podTemplate(label: 'mypod', cloud: 'openshift', containers: [
    containerTemplate(name: 'hogajama-maven', image: 'gdhet/hogarama-jenkins-slave-maven-rhel7-docker:3.5.0-jdk-8u144b01', ttyEnabled: true, command: 'cat',
                      workingDir: '/home/jenkins',
                      alwaysPullImage: true,
                      resourceRequestCpu: '100m',
                      resourceLimitCpu: '200m',
                      resourceRequestMemory: '512Mi',
                      resourceLimitMemory: '1024Mi',
                      volumes: [persistentVolumeClaim(mountPath: '/.m2/repository', claimName: 'maven-repo', readOnly: false)])
  ]) {

    node('mypod') {
        stage('Build') {
          git url: '${GIT_REPO}', branch: "${GIT_REF}"
          container('hogajama-maven') {
            sh "mvn clean install -f Hogajama/pom.xml"
          }
       }
   }
}
