podTemplate(name: 'mavenPod', label: 'mavenPod', namepsace: 'hogarama-buildserver', cloud: 'openshift', containers: [
  /**containerTemplate(name: 'hogarama_maven',
                    image: 'gdhet/hogarama-jenkins-slave-maven-rhel7-docker:3.5.0-jdk-8u144b01',
                    ttyEnabled: true,
                    command: 'cat',
                    livenessProbe: containerLivenessProbe( execArgs: 'ls ${HOME}', initialDelaySeconds: 10, timeoutSeconds: 5, failureThreshold: 10, periodSeconds: 10, successThreshold: 1))],
                    volumes: [persistentVolumeClaim(mountPath: '/.m2/repository', claimName: 'maven-repo', readOnly: false)]) {
*/

  containerTemplate(name: 'maven', livenessProbe: containerLivenessProbe( execArgs: 'ls ${HOME}', initialDelaySeconds: 10, timeoutSeconds: 5, failureThreshold: 10, periodSeconds: 10, successThreshold: 1))],
  volumes: [persistentVolumeClaim(mountPath: '/.m2/repository', claimName: 'maven-repo', readOnly: false)]) {

  node('mavenPod') {
    stage('build') {
      container('maven') {
        
      }
    }
  }
}
