podTemplate(label: 'mypod', cloud: 'openshift', containers: [
    containerTemplate(name: 'mqtt-client-maven-build', image: 'maven', ttyEnabled: true, command: 'cat',
                      workingDir: '/home/jenkins',
                      alwaysPullImage: true,
                      resourceRequestCpu: '1000m',
                      resourceLimitCpu: '2000m',
                      resourceRequestMemory: '512Mi',
                      resourceLimitMemory: '1024Mi',
                      volumes: [persistentVolumeClaim(mountPath: '/.m2', claimName: 'maven-repo', readOnly: false)])
  ]) {

    node('mypod') {
        stage('Build') {
          git url: "${GIT_REPO}", branch: "${GIT_REF}"
          container('mqtt-client-maven-build') {
            sh "mvn -s /.m2/settings.xml clean test -f mqtt-client-java/mqtt-client/pom.xml"
          }
        }
    }
}
